// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/blacklist.go
//
// Generated by this command:
//
//	mockgen -source=internal/store/blacklist.go -destination=internal/mocks/blacklist_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenBlacklist is a mock of TokenBlacklist interface.
type MockTokenBlacklist struct {
	ctrl     *gomock.Controller
	recorder *MockTokenBlacklistMockRecorder
	isgomock struct{}
}

// MockTokenBlacklistMockRecorder is the mock recorder for MockTokenBlacklist.
type MockTokenBlacklistMockRecorder struct {
	mock *MockTokenBlacklist
}

// NewMockTokenBlacklist creates a new mock instance.
func NewMockTokenBlacklist(ctrl *gomock.Controller) *MockTokenBlacklist {
	mock := &MockTokenBlacklist{ctrl: ctrl}
	mock.recorder = &MockTokenBlacklistMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenBlacklist) EXPECT() *MockTokenBlacklistMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTokenBlacklist) Add(token string, expiresAt time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", token, expiresAt)
}

// Add indicates an expected call of Add.
func (mr *MockTokenBlacklistMockRecorder) Add(token, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTokenBlacklist)(nil).Add), token, expiresAt)
}

// IsBlacklisted mocks base method.
func (m *MockTokenBlacklist) IsBlacklisted(token string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBlacklisted", token)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBlacklisted indicates an expected call of IsBlacklisted.
func (mr *MockTokenBlacklistMockRecorder) IsBlacklisted(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBlacklisted", reflect.TypeOf((*MockTokenBlacklist)(nil).IsBlacklisted), token)
}
