// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/checkout_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/checkout_repository.go -destination=internal/mocks/checkout_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "flash-sale-be/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockCheckoutRepository is a mock of CheckoutRepository interface.
type MockCheckoutRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckoutRepositoryMockRecorder
	isgomock struct{}
}

// MockCheckoutRepositoryMockRecorder is the mock recorder for MockCheckoutRepository.
type MockCheckoutRepositoryMockRecorder struct {
	mock *MockCheckoutRepository
}

// NewMockCheckoutRepository creates a new mock instance.
func NewMockCheckoutRepository(ctrl *gomock.Controller) *MockCheckoutRepository {
	mock := &MockCheckoutRepository{ctrl: ctrl}
	mock.recorder = &MockCheckoutRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckoutRepository) EXPECT() *MockCheckoutRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCheckoutRepository) Create(checkout *domain.Checkout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", checkout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCheckoutRepositoryMockRecorder) Create(checkout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCheckoutRepository)(nil).Create), checkout)
}

// CreateWithTransaction mocks base method.
func (m *MockCheckoutRepository) CreateWithTransaction(tx *gorm.DB, checkout *domain.Checkout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTransaction", tx, checkout)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTransaction indicates an expected call of CreateWithTransaction.
func (mr *MockCheckoutRepositoryMockRecorder) CreateWithTransaction(tx, checkout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTransaction", reflect.TypeOf((*MockCheckoutRepository)(nil).CreateWithTransaction), tx, checkout)
}

// CreateWithTx mocks base method.
func (m *MockCheckoutRepository) CreateWithTx(tx *gorm.DB, checkout *domain.Checkout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", tx, checkout)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockCheckoutRepositoryMockRecorder) CreateWithTx(tx, checkout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockCheckoutRepository)(nil).CreateWithTx), tx, checkout)
}
