// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\service\checkout_service.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\service\checkout_service.go -destination=.\internal\mocks\checkout_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "flash-sale-be/internal/dto"
	queue "flash-sale-be/internal/queue"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCheckoutService is a mock of CheckoutService interface.
type MockCheckoutService struct {
	ctrl     *gomock.Controller
	recorder *MockCheckoutServiceMockRecorder
	isgomock struct{}
}

// MockCheckoutServiceMockRecorder is the mock recorder for MockCheckoutService.
type MockCheckoutServiceMockRecorder struct {
	mock *MockCheckoutService
}

// NewMockCheckoutService creates a new mock instance.
func NewMockCheckoutService(ctrl *gomock.Controller) *MockCheckoutService {
	mock := &MockCheckoutService{ctrl: ctrl}
	mock.recorder = &MockCheckoutServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckoutService) EXPECT() *MockCheckoutServiceMockRecorder {
	return m.recorder
}

// EnqueueCheckout mocks base method.
func (m *MockCheckoutService) EnqueueCheckout(ctx context.Context, userID string, req *dto.CheckoutRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueCheckout", ctx, userID, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnqueueCheckout indicates an expected call of EnqueueCheckout.
func (mr *MockCheckoutServiceMockRecorder) EnqueueCheckout(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueCheckout", reflect.TypeOf((*MockCheckoutService)(nil).EnqueueCheckout), ctx, userID, req)
}

// GetCheckoutsByUser mocks base method.
func (m *MockCheckoutService) GetCheckoutsByUser(ctx context.Context, userID string) ([]*dto.CheckoutListItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckoutsByUser", ctx, userID)
	ret0, _ := ret[0].([]*dto.CheckoutListItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckoutsByUser indicates an expected call of GetCheckoutsByUser.
func (mr *MockCheckoutServiceMockRecorder) GetCheckoutsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckoutsByUser", reflect.TypeOf((*MockCheckoutService)(nil).GetCheckoutsByUser), ctx, userID)
}

// ProcessCheckoutJob mocks base method.
func (m *MockCheckoutService) ProcessCheckoutJob(ctx context.Context, job *queue.CheckoutJob) (*dto.CheckoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessCheckoutJob", ctx, job)
	ret0, _ := ret[0].(*dto.CheckoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessCheckoutJob indicates an expected call of ProcessCheckoutJob.
func (mr *MockCheckoutServiceMockRecorder) ProcessCheckoutJob(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessCheckoutJob", reflect.TypeOf((*MockCheckoutService)(nil).ProcessCheckoutJob), ctx, job)
}
