// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\repository\products_repository.go
//
// Generated by this command:
//
//	mockgen -source=.\internal\repository\products_repository.go -destination=.\internal\mocks\products_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "flash-sale-be/internal/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockProductsRepository is a mock of ProductsRepository interface.
type MockProductsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductsRepositoryMockRecorder
	isgomock struct{}
}

// MockProductsRepositoryMockRecorder is the mock recorder for MockProductsRepository.
type MockProductsRepositoryMockRecorder struct {
	mock *MockProductsRepository
}

// NewMockProductsRepository creates a new mock instance.
func NewMockProductsRepository(ctrl *gomock.Controller) *MockProductsRepository {
	mock := &MockProductsRepository{ctrl: ctrl}
	mock.recorder = &MockProductsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductsRepository) EXPECT() *MockProductsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductsRepository) Create(product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductsRepositoryMockRecorder) Create(product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductsRepository)(nil).Create), product)
}

// DecrementStock mocks base method.
func (m *MockProductsRepository) DecrementStock(tx *gorm.DB, productID uuid.UUID, quantity int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementStock", tx, productID, quantity)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementStock indicates an expected call of DecrementStock.
func (mr *MockProductsRepositoryMockRecorder) DecrementStock(tx, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementStock", reflect.TypeOf((*MockProductsRepository)(nil).DecrementStock), tx, productID, quantity)
}

// Delete mocks base method.
func (m *MockProductsRepository) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductsRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductsRepository)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockProductsRepository) GetAll(createdBy uuid.UUID) ([]*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", createdBy)
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockProductsRepositoryMockRecorder) GetAll(createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockProductsRepository)(nil).GetAll), createdBy)
}

// GetAllNotDeleted mocks base method.
func (m *MockProductsRepository) GetAllNotDeleted() ([]*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotDeleted")
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotDeleted indicates an expected call of GetAllNotDeleted.
func (mr *MockProductsRepositoryMockRecorder) GetAllNotDeleted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotDeleted", reflect.TypeOf((*MockProductsRepository)(nil).GetAllNotDeleted))
}

// GetById mocks base method.
func (m *MockProductsRepository) GetById(id uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockProductsRepositoryMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockProductsRepository)(nil).GetById), id)
}

// GetByIdForUpdate mocks base method.
func (m *MockProductsRepository) GetByIdForUpdate(tx *gorm.DB, id uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdForUpdate", tx, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdForUpdate indicates an expected call of GetByIdForUpdate.
func (mr *MockProductsRepositoryMockRecorder) GetByIdForUpdate(tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdForUpdate", reflect.TypeOf((*MockProductsRepository)(nil).GetByIdForUpdate), tx, id)
}

// GetByIds mocks base method.
func (m *MockProductsRepository) GetByIds(ids []uuid.UUID) ([]*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIds", ids)
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockProductsRepositoryMockRecorder) GetByIds(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockProductsRepository)(nil).GetByIds), ids)
}

// GetByName mocks base method.
func (m *MockProductsRepository) GetByName(name string, id uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockProductsRepositoryMockRecorder) GetByName(name, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockProductsRepository)(nil).GetByName), name, id)
}

// Update mocks base method.
func (m *MockProductsRepository) Update(product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProductsRepositoryMockRecorder) Update(product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductsRepository)(nil).Update), product)
}
