// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/products_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/products_service.go -destination=internal/mocks/products_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "flash-sale-be/internal/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProductsService is a mock of ProductsService interface.
type MockProductsService struct {
	ctrl     *gomock.Controller
	recorder *MockProductsServiceMockRecorder
	isgomock struct{}
}

// MockProductsServiceMockRecorder is the mock recorder for MockProductsService.
type MockProductsServiceMockRecorder struct {
	mock *MockProductsService
}

// NewMockProductsService creates a new mock instance.
func NewMockProductsService(ctrl *gomock.Controller) *MockProductsService {
	mock := &MockProductsService{ctrl: ctrl}
	mock.recorder = &MockProductsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductsService) EXPECT() *MockProductsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductsService) Create(req *dto.CreateProductRequest) (*dto.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", req)
	ret0, _ := ret[0].(*dto.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProductsServiceMockRecorder) Create(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductsService)(nil).Create), req)
}

// Delete mocks base method.
func (m *MockProductsService) Delete(id, createdBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, createdBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductsServiceMockRecorder) Delete(id, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductsService)(nil).Delete), id, createdBy)
}

// GetAll mocks base method.
func (m *MockProductsService) GetAll() ([]*dto.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*dto.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockProductsServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockProductsService)(nil).GetAll))
}

// GetAllByUser mocks base method.
func (m *MockProductsService) GetAllByUser(createdBy string) ([]*dto.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByUser", createdBy)
	ret0, _ := ret[0].([]*dto.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByUser indicates an expected call of GetAllByUser.
func (mr *MockProductsServiceMockRecorder) GetAllByUser(createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByUser", reflect.TypeOf((*MockProductsService)(nil).GetAllByUser), createdBy)
}

// GetById mocks base method.
func (m *MockProductsService) GetById(id, createdBy string) (*dto.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id, createdBy)
	ret0, _ := ret[0].(*dto.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockProductsServiceMockRecorder) GetById(id, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockProductsService)(nil).GetById), id, createdBy)
}

// Update mocks base method.
func (m *MockProductsService) Update(id string, req *dto.UpdateProductRequest) (*dto.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, req)
	ret0, _ := ret[0].(*dto.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProductsServiceMockRecorder) Update(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductsService)(nil).Update), id, req)
}
