// Code generated by MockGen. DO NOT EDIT.
// Source: internal/queue/redis.go
//
// Generated by this command:
//
//	mockgen -source=internal/queue/redis.go -destination=internal/mocks/queue_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	queue "flash-sale-be/internal/queue"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
	isgomock struct{}
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// DequeueCheckout mocks base method.
func (m *MockQueue) DequeueCheckout(ctx context.Context) (*queue.CheckoutJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DequeueCheckout", ctx)
	ret0, _ := ret[0].(*queue.CheckoutJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DequeueCheckout indicates an expected call of DequeueCheckout.
func (mr *MockQueueMockRecorder) DequeueCheckout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DequeueCheckout", reflect.TypeOf((*MockQueue)(nil).DequeueCheckout), ctx)
}

// EnqueueCheckout mocks base method.
func (m *MockQueue) EnqueueCheckout(ctx context.Context, job queue.CheckoutJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueCheckout", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueCheckout indicates an expected call of EnqueueCheckout.
func (mr *MockQueueMockRecorder) EnqueueCheckout(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueCheckout", reflect.TypeOf((*MockQueue)(nil).EnqueueCheckout), ctx, job)
}
